# Generated by Django 5.0.6 on 2024-06-08 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_talentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_tasks', models.TextField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('seniority', models.CharField(choices=[('INTERN', 'Intern'), ('JR', 'Junior'), ('MID', 'Mid-level'), ('SR', 'Senior'), ('LEAD', 'Lead'), ('PRINCIPAL', 'Principal'), ('ARCHITECT', 'Architect'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('VP', 'Vice President'), ('CLEVEL', 'C-Level')], max_length=255)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary'), ('REMOTE', 'Remote')], max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
