# Generated by Django 5.0.6 on 2024-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('FR', 'French'), ('ES', 'Spanish'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('KO', 'Korean'), ('RU', 'Russian'), ('PT', 'Portuguese'), ('IT', 'Italian'), ('NL', 'Dutch'), ('HU', 'Hungarian'), ('PL', 'Polish'), ('SV', 'Swedish'), ('DA', 'Danish'), ('NO', 'Norwegian'), ('FI', 'Finnish'), ('TR', 'Turkish'), ('AR', 'Arabic'), ('HE', 'Hebrew'), ('HI', 'Hindi'), ('BN', 'Bengali'), ('MS', 'Malay'), ('VI', 'Vietnamese'), ('TH', 'Thai'), ('ID', 'Indonesian'), ('TL', 'Tagalog'), ('UK', 'Ukrainian'), ('CS', 'Czech'), ('EL', 'Greek'), ('RO', 'Romanian'), ('BG', 'Bulgarian'), ('HR', 'Croatian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SR', 'Serbian')], max_length=255)),
                ('level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('FLU', 'Fluent'), ('NAT', 'Native')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.ManyToManyField(related_name='jobs', to='core.languageskill'),
        ),
    ]
