# Generated by Django 5.0.6 on 2024-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_languageskill_job_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.languageskill'),
        ),
    ]
