# Generated by Django 5.0.6 on 2024-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('TECH_PY', 'Python'), ('TECH_JS', 'JavaScript'), ('TECH_JV', 'Java'), ('TECH_CS', 'C#'), ('TECH_CPP', 'C++'), ('TECH_RB', 'Ruby'), ('TECH_PHP', 'PHP'), ('TECH_SW', 'Swift'), ('TECH_GO', 'Go'), ('TECH_RU', 'Rust'), ('TECH_HT', 'HTML'), ('TECH_CSS', 'CSS'), ('TECH_RE', 'React'), ('TECH_ANG', 'Angular'), ('TECH_VU', 'Vue.js'), ('TECH_DJ', 'Django'), ('TECH_FL', 'Flask'), ('TECH_ND', 'Node.js'), ('TECH_AS', 'ASP.NET'), ('TECH_SQL', 'SQL'), ('TECH_MY', 'MySQL'), ('TECH_PG', 'PostgreSQL'), ('TECH_MO', 'MongoDB'), ('TECH_OR', 'Oracle'), ('TECH_SL', 'SQLite'), ('TECH_MS', 'Microsoft SQL Server'), ('TECH_AW', 'Amazon Web Services (AWS)'), ('TECH_AZ', 'Microsoft Azure'), ('TECH_GC', 'Google Cloud Platform (GCP)'), ('TECH_IB', 'IBM Cloud'), ('TECH_DO', 'Docker'), ('TECH_KU', 'Kubernetes'), ('TECH_JE', 'Jenkins'), ('TECH_TRA', 'Travis CI'), ('TECH_CI', 'CircleCI'), ('TECH_CC', 'CI/CD'), ('TECH_ANS', 'Ansible'), ('TECH_PU', 'Puppet'), ('TECH_CH', 'Chef'), ('TECH_GI', 'Git'), ('TECH_GH', 'GitHub'), ('TECH_GL', 'GitLab'), ('TECH_BB', 'Bitbucket'), ('TECH_LI', 'Linux'), ('TECH_WI', 'Windows'), ('TECH_MA', 'macOS'), ('TECH_UN', 'Unix'), ('TECH_TC', 'TCP/IP'), ('TECH_DN', 'DNS'), ('TECH_DH', 'DHCP'), ('TECH_VP', 'VPN'), ('TECH_FW', 'Firewall Management'), ('TECH_EH', 'Ethical Hacking'), ('TECH_PT', 'Penetration Testing'), ('TECH_NS', 'Network Security'), ('TECH_IS', 'Information Security'), ('TECH_SE', 'Security Information and Event Management (SIEM)'), ('TECH_AG', 'Agile Methodologies'), ('TECH_SC', 'Scrum'), ('TECH_KA', 'Kanban'), ('TECH_TD', 'Test-Driven Development (TDD)'), ('TECH_BD', 'Behavior-Driven Development (BDD)'), ('TECH_AD', 'Android Development'), ('TECH_IO', 'iOS Development'), ('TECH_RN', 'React Native'), ('TECH_FLU', 'Flutter'), ('TECH_DM', 'Data Mining'), ('TECH_ML', 'Machine Learning'), ('TECH_DL', 'Deep Learning'), ('TECH_DV', 'Data Visualization'), ('TECH_PD', 'Pandas'), ('TECH_NP', 'NumPy'), ('TECH_R', 'R Programming'), ('TECH_MT', 'MATLAB'), ('TECH_BA', 'Bash/Shell Scripting'), ('TECH_PS', 'PowerShell'), ('TECH_PE', 'Perl'), ('TECH_SAP', 'SAP'), ('TECH_SF', 'Salesforce'), ('TECH_OE', 'Oracle ERP'), ('TECH_JI', 'JIRA'), ('TECH_TRL', 'Trello'), ('TECH_ASA', 'Asana')], max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, related_name='tech_skills', to='core.technicalskill'),
        ),
    ]
