# Generated by Django 5.0.6 on 2024-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_technicalskill_job_technical_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('PERS_COM', 'Communication'), ('PERS_TW', 'Teamwork'), ('PERS_PS', 'Problem Solving'), ('PERS_TM', 'Time Management'), ('PERS_AD', 'Adaptability'), ('PERS_CRE', 'Creativity'), ('PERS_LS', 'Leadership'), ('PERS_WE', 'Work Ethic'), ('PERS_IP', 'Interpersonal Skills'), ('PERS_ATD', 'Attention to Detail'), ('PERS_CT', 'Critical Thinking'), ('PERS_PA', 'Positive Attitude'), ('PERS_CFR', 'Conflict Resolution'), ('PERS_EI', 'Emotional Intelligence'), ('PERS_DM', 'Decision Making'), ('PERS_OR', 'Organization'), ('PERS_SM', 'Stress Management'), ('PERS_PE', 'Persistence'), ('PERS_FL', 'Flexibility'), ('PERS_IN', 'Initiative'), ('PERS_CS', 'Customer Service')], max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.technicalskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='personal_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.personalskill'),
        ),
    ]
