"""
Enums for choice fields.
"""
from django.db import models


class Role(models.TextChoices):
    """User roles."""
    ADMIN = "ADMIN", 'Admin'
    COMPANY = "COMPANY", 'Company'
    TALENT = "TALENT", 'Talent'


class TechSkill(models.TextChoices):
    """Technical skills."""
    PYTHON = 'TECH_PY', 'Python'
    JAVASCRIPT = 'TECH_JS', 'JavaScript'
    JAVA = 'TECH_JV', 'Java'
    C_SHARP = 'TECH_CS', 'C#'
    CPP = 'TECH_CPP', 'C++'
    RUBY = 'TECH_RB', 'Ruby'
    PHP = 'TECH_PHP', 'PHP'
    SWIFT = 'TECH_SW', 'Swift'
    GO = 'TECH_GO', 'Go'
    RUST = 'TECH_RU', 'Rust'
    HTML = 'TECH_HT', 'HTML'
    CSS = 'TECH_CS', 'CSS'
    REACT = 'TECH_RE', 'React'
    ANGULAR = 'TECH_AN', 'Angular'
    VUEJS = 'TECH_VU', 'Vue.js'
    DJANGO = 'TECH_DJ', 'Django'
    FLASK = 'TECH_FL', 'Flask'
    NODEJS = 'TECH_ND', 'Node.js'
    ASPNET = 'TECH_AS', 'ASP.NET'
    SQL = 'TECH_SQL', 'SQL'
    MYSQL = 'TECH_MY', 'MySQL'
    POSTGRESQL = 'TECH_PG', 'PostgreSQL'
    MONGODB = 'TECH_MO', 'MongoDB'
    ORACLE_DB = 'TECH_OR', 'Oracle'
    SQLITE = 'TECH_SL', 'SQLite'
    MS_SQL_SERVER = 'TECH_MS', 'Microsoft SQL Server'
    AWS = 'TECH_AW', 'Amazon Web Services (AWS)'
    AZURE = 'TECH_AZ', 'Microsoft Azure'
    GCP = 'TECH_GC', 'Google Cloud Platform (GCP)'
    IBM_CLOUD = 'TECH_IB', 'IBM Cloud'
    DOCKER = 'TECH_DO', 'Docker'
    KUBERNETES = 'TECH_KU', 'Kubernetes'
    JENKINS = 'TECH_JE', 'Jenkins'
    TRAVIS_CI = 'TECH_TR', 'Travis CI'
    CIRCLECI = 'TECH_CI', 'CircleCI'
    CI_CD = 'TECH_CC', 'CI/CD'
    ANSIBLE = 'TECH_AN', 'Ansible'
    PUPPET = 'TECH_PU', 'Puppet'
    CHEF = 'TECH_CH', 'Chef'
    GIT = 'TECH_GI', 'Git'
    GITHUB = 'TECH_GH', 'GitHub'
    GITLAB = 'TECH_GL', 'GitLab'
    BITBUCKET = 'TECH_BB', 'Bitbucket'
    LINUX = 'TECH_LI', 'Linux'
    WINDOWS = 'TECH_WI', 'Windows'
    MACOS = 'TECH_MA', 'macOS'
    UNIX = 'TECH_UN', 'Unix'
    TCP_IP = 'TECH_TC', 'TCP/IP'
    DNS = 'TECH_DN', 'DNS'
    DHCP = 'TECH_DH', 'DHCP'
    VPN = 'TECH_VP', 'VPN'
    FIREWALL = 'TECH_FW', 'Firewall Management'
    ETHICAL_HACKING = 'TECH_EH', 'Ethical Hacking'
    PEN_TESTING = 'TECH_PT', 'Penetration Testing'
    NETWORK_SECURITY = 'TECH_NS', 'Network Security'
    INFO_SECURITY = 'TECH_IS', 'Information Security'
    SIEM = 'TECH_SE', 'Security Information and Event Management (SIEM)'
    AGILE = 'TECH_AG', 'Agile Methodologies'
    SCRUM = 'TECH_SC', 'Scrum'
    KANBAN = 'TECH_KA', 'Kanban'
    TDD = 'TECH_TD', 'Test-Driven Development (TDD)'
    BDD = 'TECH_BD', 'Behavior-Driven Development (BDD)'
    ANDROID_DEV = 'TECH_AD', 'Android Development'
    IOS_DEV = 'TECH_IO', 'iOS Development'
    REACT_NATIVE = 'TECH_RN', 'React Native'
    FLUTTER = 'TECH_FLU', 'Flutter'
    DATA_MINING = 'TECH_DM', 'Data Mining'
    MACHINE_LEARNING = 'TECH_ML', 'Machine Learning'
    DEEP_LEARNING = 'TECH_DL', 'Deep Learning'
    DATA_VISUALIZATION = 'TECH_DV', 'Data Visualization'
    PANDAS = 'TECH_PD', 'Pandas'
    NUMPY = 'TECH_NP', 'NumPy'
    R = 'TECH_R', 'R Programming'
    MATLAB = 'TECH_MT', 'MATLAB'
    BASH = 'TECH_BA', 'Bash/Shell Scripting'
    POWERSHELL = 'TECH_PS', 'PowerShell'
    PERL = 'TECH_PE', 'Perl'
    SAP = 'TECH_SAP', 'SAP'
    SALESFORCE = 'TECH_SF', 'Salesforce'
    ORACLE_ERP = 'TECH_OE', 'Oracle ERP'
    JIRA = 'TECH_JI', 'JIRA'
    TRELLO = 'TECH_TR', 'Trello'
    ASANA = 'TECH_ASA', 'Asana'


class PersSkill(models.TextChoices):
    """Personality skills."""
    COMMUNICATION = 'PERS_COM', 'Communication'
    TEAMWORK = 'PERS_TW', 'Teamwork'
    PROBLEM_SOLVING = 'PERS_PS', 'Problem Solving'
    TIME_MANAGEMENT = 'PERS_TM', 'Time Management'
    ADAPTABILITY = 'PERS_AD', 'Adaptability'
    CREATIVITY = 'PERS_CR', 'Creativity'
    LEADERSHIP = 'PERS_LS', 'Leadership'
    WORK_ETHIC = 'PERS_WE', 'Work Ethic'
    INTERPERSONAL = 'PERS_IP', 'Interpersonal Skills'
    ATTENTION_TO_DETAIL = 'PERS_ATD', 'Attention to Detail'
    CRITICAL_THINKING = 'PERS_CT', 'Critical Thinking'
    POSITIVE_ATTITUDE = 'PERS_PA', 'Positive Attitude'
    CONFLICT_RESOLUTION = 'PERS_CR', 'Conflict Resolution'
    EMOTIONAL_INTELLIGENCE = 'PERS_EI', 'Emotional Intelligence'
    DECISION_MAKING = 'PERS_DM', 'Decision Making'
    ORGANIZATION = 'PERS_OR', 'Organization'
    STRESS_MANAGEMENT = 'PERS_SM', 'Stress Management'
    PERSISTENCE = 'PERS_PE', 'Persistence'
    FLEXIBILITY = 'PERS_FL', 'Flexibility'
    INITIATIVE = 'PERS_IN', 'Initiative'
    CUSTOMER_SERVICE = 'PERS_CS', 'Customer Service'


class LangSkill(models.TextChoices):
    """Language skills."""
    ENGLISH = 'EN', 'English'
    GERMAN = 'DE', 'German'
    FRENCH = 'FR', 'French'
    SPANISH = 'ES', 'Spanish'
    CHINESE = 'ZH', 'Chinese'
    JAPANESE = 'JA', 'Japanese'
    KOREAN = 'KO', 'Korean'
    RUSSIAN = 'RU', 'Russian'
    PORTUGUESE = 'PT', 'Portuguese'
    ITALIAN = 'IT', 'Italian'
    DUTCH = 'NL', 'Dutch'
    HUNGARIAN = 'HU', 'Hungarian'
    POLISH = 'PL', 'Polish'
    SWEDISH = 'SV', 'Swedish'
    DANISH = 'DA', 'Danish'
    NORWEGIAN = 'NO', 'Norwegian'
    FINNISH = 'FI', 'Finnish'
    TURKISH = 'TR', 'Turkish'
    ARABIC = 'AR', 'Arabic'
    HEBREW = 'HE', 'Hebrew'
    HINDI = 'HI', 'Hindi'
    BENGALI = 'BN', 'Bengali'
    MALAY = 'MS', 'Malay'
    VIETNAMESE = 'VI', 'Vietnamese'
    THAI = 'TH', 'Thai'
    INDONESIAN = 'ID', 'Indonesian'
    TAGALOG = 'TL', 'Tagalog'
    UKRAINIAN = 'UK', 'Ukrainian'
    CZECH = 'CS', 'Czech'
    GREEK = 'EL', 'Greek'
    ROMANIAN = 'RO', 'Romanian'
    BULGARIAN = 'BG', 'Bulgarian'
    CROATIAN = 'HR', 'Croatian'
    SLOVAK = 'SK', 'Slovak'
    SLOVENIAN = 'SL', 'Slovenian'
    SERBIAN = 'SR', 'Serbian'


class LangProf(models.TextChoices):
    """Language proficiency."""
    BEGINNER = 'BEG', 'Beginner'
    INTERMEDIATE = 'INT', 'Intermediate'
    ADVANCED = 'ADV', 'Advanced'
    FLUENT = 'FLU', 'Fluent'
    NATIVE = 'NAT', 'Native'


class Education(models.TextChoices):
    """Edication choices."""
    NONE = 'NONE', 'None'
    HIGH_SCHOOL = 'HS', 'High School Diploma'
    ASSOCIATE_DEGREE = 'AD', 'Associate Degree'
    BACHELORS_DEGREE = 'BD', 'Bachelor\'s Degree'
    MASTERS_DEGREE = 'MD', 'Master\'s Degree'
    DOCTORATE = 'DOC', 'Doctorate (PhD, EdD, etc.)'
    PROFESSIONAL_CERTIFICATION = 'PC', 'Professional Certification'
    TRADE_SCHOOL = 'TS', 'Trade School'
    OTHER = 'OTH', 'Other'


class Seniority(models.TextChoices):
    """Seniority level."""
    INTERN = 'INTERN', 'Intern'
    JUNIOR = 'JR', 'Junior'
    MID_LEVEL = 'MID', 'Mid-level'
    SENIOR = 'SR', 'Senior'
    LEAD = 'LEAD', 'Lead'
    PRINCIPAL = 'PRINCIPAL', 'Principal'
    ARCHITECT = 'ARCHITECT', 'Architect'
    MANAGER = 'MANAGER', 'Manager'
    DIRECTOR = 'DIRECTOR', 'Director'
    VICE_PRESIDENT = 'VP', 'Vice President'
    C_LEVEL = 'CLEVEL', 'C-Level'


class Area(models.TextChoices):
    """It fields and areas."""
    IT_SUPPORT = 'ITS', 'IT Support'
    WEB_DEVELOPMENT = 'WEB', 'Web Development'
    BACKEND_DEVELOPMENT = 'BACKEND', 'Backend Development'
    FRONTEND_DEVELOPMENT = 'FRONTEND', 'Frontend Development'
    FULL_STACK_DEVELOPMENT = 'FULLSTACK', 'Full Stack Development'
    DEVOPS = 'DEVOPS', 'DevOps'
    DATABASE_ADMINISTRATION = 'DBA', 'Database Administration'
    SECURITY = 'SEC', 'Security'
    NETWORKING = 'NET', 'Networking'
    CLOUD_COMPUTING = 'CLOUD', 'Cloud Computing'
    DATA_SCIENCE = 'DATA', 'Data Science'
    MACHINE_LEARNING = 'ML', 'Machine Learning'
    AI = 'AI', 'Artificial Intelligence'
    MOBILE_DEVELOPMENT = 'MOBILE', 'Mobile Development'
    GAME_DEVELOPMENT = 'GAME', 'Game Development'
    SOFTWARE_ENGINEERING = 'SOFTENG', 'Software Engineering'
    SYSTEM_ADMINISTRATION = 'SYSADMIN', 'System Administration'
    QA_TESTING = 'QA', 'QA & Testing'
    PROJECT_MANAGEMENT = 'PM', 'Project Management'
    PRODUCT_MANAGEMENT = 'PRODMAN', 'Product Management'
    UI_UX_DESIGN = 'UIUX', 'UI/UX Design'
    TECHNICAL_WRITING = 'TECHWRITE', 'Technical Writing'
    BUSINESS_ANALYSIS = 'BA', 'Business Analysis'
    TECHNICAL_SUPPORT = 'TECHSUP', 'Technical Support'
    CONSULTING = 'CONSULT', 'Consulting'
    SALES_ENGINEERING = 'SALESENG', 'Sales Engineering'
    IT_TRAINING = 'ITTRAIN', 'IT Training'


class NoticePeriod(models.TextChoices):
    """Starting date/notice period."""
    IMMEDIATELY = 'IMM', 'Immediately'
    ONE_MONTH = '1M', '1 month'
    TWO_MONTHS = '2M', '2 months'
    THREE_MONTHS = '3M', '3 months'
    MORE_THAN_THREE_MONTHS = 'MORE', 'More than 3 months'
    FLEXIBLE = 'FLEX', 'Flexible'
    OTHER = 'OTHER', 'Other'


class Employment(models.TextChoices):
    """Employment type."""
    FULL_TIME = 'FULL_TIME', 'Full-Time'
    PART_TIME = 'PART_TIME', 'Part-Time'
    CONTRACT = 'CONTRACT', 'Contract'
    FREELANCE = 'FREELANCE', 'Freelance'
    INTERNSHIP = 'INTERNSHIP', 'Internship'
    TEMPORARY = 'TEMPORARY', 'Temporary'
    REMOTE = 'REMOTE', 'Remote'
